name: test

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
      - name: Test with pytest
        run: |
          pytest --cov-report=xml --cov=src/PPTT
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1